const std = @import("std");
const canonical_json = @import("canonical_json.zig");

pub const PublicTrialSchema = "hylo-trial/v2";
pub const CustodySchema = "hylo-trial-custody/v1";
pub const RevealSchema = "hylo-trial-reveal/v2";
pub const CustodyOpeningSchema = "hylo-trial-custody-opening/v1";
pub const TreatmentOpeningSchema = "hylo-treatment-opening/v1";
pub const TreatmentMaterializationOpeningSchema = "hylo-treatment-materialization-opening/v1";
pub const TargetOpeningSchema = "hylo-target-opening/v1";
pub const ChangeOpeningSchema = "hylo-change-opening/v1";
pub const WitnessOpeningSchema = "hylo-intervention-witness-opening/v1";
pub const TargetCommonProjectionOpeningSchema = "hylo-target-common-projection-opening/v1";
pub const SourceSelectionOpeningSchema = "hylo-source-selection-opening/v1";
pub const ArmMapSchema = "hylo-arm-map/v1";
pub const MaterializerValidationSchema = "hylo-materializer-validation/v1";

fn object(value: std.json.Value) !std.json.ObjectMap {
    return switch (value) {
        .object => |map| map,
        else => error.ObjectRequired,
    };
}

fn array(value: std.json.Value) !std.json.Array {
    return switch (value) {
        .array => |items| items,
        else => error.ArrayRequired,
    };
}

fn string(value: std.json.Value) ![]const u8 {
    return switch (value) {
        .string => |text| text,
        else => error.StringRequired,
    };
}

fn boolean(value: std.json.Value) !bool {
    return switch (value) {
        .bool => |flag| flag,
        else => error.BooleanRequired,
    };
}

fn required(map: std.json.ObjectMap, key: []const u8) !std.json.Value {
    return map.get(key) orelse error.RequiredFieldMissing;
}

fn requiredObject(map: std.json.ObjectMap, key: []const u8) !std.json.ObjectMap {
    return object(try required(map, key));
}

fn requiredArray(map: std.json.ObjectMap, key: []const u8) !std.json.Array {
    return array(try required(map, key));
}

fn requiredString(map: std.json.ObjectMap, key: []const u8) ![]const u8 {
    return string(try required(map, key));
}

fn requireExactKeys(map: std.json.ObjectMap, expected: []const []const u8) !void {
    if (map.count() != expected.len) return error.CustodyShapeInvalid;
    for (expected) |key| _ = map.get(key) orelse return error.CustodyShapeInvalid;
}

fn validateFingerprint(value: []const u8) !void {
    if (value.len != "sha256:".len + 64 or !std.mem.startsWith(u8, value, "sha256:")) {
        return error.FingerprintInvalid;
    }
    for (value["sha256:".len..]) |byte| {
        if (!std.ascii.isDigit(byte) and !(byte >= 'a' and byte <= 'f')) {
            return error.FingerprintInvalid;
        }
    }
}

fn validateLowerHexNonce(value: []const u8, expected_len: usize) !void {
    if (value.len != expected_len) return error.CustodyNonceInvalid;
    for (value) |byte| {
        if (!std.ascii.isDigit(byte) and !(byte >= 'a' and byte <= 'f')) {
            return error.CustodyNonceInvalid;
        }
    }
}

/// The arm-map opening retains the 16-byte nonce generated by the v1 trial
/// compiler, encoded as exactly 32 bare lowercase hexadecimal characters.
pub fn validateArmMapNonce(value: []const u8) !void {
    return validateLowerHexNonce(value, 32);
}

/// Every nonce generated specifically for `hylo-trial-custody/v1` is a full
/// SHA-256 digest encoded as exactly 64 bare lowercase hexadecimal characters.
pub fn validateNonce(value: []const u8) !void {
    return validateLowerHexNonce(value, 64);
}

pub fn digestValueAlloc(allocator: std.mem.Allocator, value: std.json.Value) ![]u8 {
    return canonical_json.digestValueAlloc(allocator, value);
}

pub fn treatmentCommitmentAlloc(
    allocator: std.mem.Allocator,
    treatment: std.json.ObjectMap,
) ![]u8 {
    var out: std.Io.Writer.Allocating = .init(allocator);
    defer out.deinit();
    try out.writer.writeAll("{\"arm_id\":");
    try canonical_json.writeCanonicalString(&out.writer, try requiredString(treatment, "arm_id"));
    try out.writer.writeAll(",\"materialization_fingerprint\":");
    try canonical_json.writeCanonicalString(
        &out.writer,
        try requiredString(treatment, "materialization_fingerprint"),
    );
    try out.writer.writeAll(",\"materialization_ref\":");
    try canonical_json.writeCanonicalString(
        &out.writer,
        try requiredString(treatment, "materialization_ref"),
    );
    try out.writer.writeAll(",\"nonce\":");
    try canonical_json.writeCanonicalString(&out.writer, try requiredString(treatment, "nonce"));
    try out.writer.writeAll(
        ",\"schema\":\"hylo-treatment-materialization-opening/v1\"," ++
            "\"value_fingerprint\":",
    );
    try canonical_json.writeCanonicalString(
        &out.writer,
        try requiredString(treatment, "value_fingerprint"),
    );
    try out.writer.writeByte('}');
    return canonical_json.digestBytesAlloc(allocator, out.written());
}

pub fn treatmentMaterializationOpeningAlloc(
    allocator: std.mem.Allocator,
    treatment: std.json.ObjectMap,
) ![]u8 {
    var out: std.Io.Writer.Allocating = .init(allocator);
    defer out.deinit();
    try out.writer.writeAll("{\"arm_id\":");
    try canonical_json.writeCanonicalString(&out.writer, try requiredString(treatment, "arm_id"));
    try out.writer.writeAll(",\"materialization_fingerprint\":");
    try canonical_json.writeCanonicalString(
        &out.writer,
        try requiredString(treatment, "materialization_fingerprint"),
    );
    try out.writer.writeAll(",\"materialization_ref\":");
    try canonical_json.writeCanonicalString(
        &out.writer,
        try requiredString(treatment, "materialization_ref"),
    );
    try out.writer.writeAll(",\"nonce\":");
    try canonical_json.writeCanonicalString(&out.writer, try requiredString(treatment, "nonce"));
    try out.writer.writeAll(
        ",\"schema\":\"hylo-treatment-materialization-opening/v1\"," ++
            "\"value_fingerprint\":",
    );
    try canonical_json.writeCanonicalString(
        &out.writer,
        try requiredString(treatment, "value_fingerprint"),
    );
    try out.writer.writeByte('}');
    return out.toOwnedSlice();
}

pub fn armMapCommitmentAlloc(
    allocator: std.mem.Allocator,
    trial_id: []const u8,
    mapping: std.json.Value,
    nonce: []const u8,
) ![]u8 {
    var out: std.Io.Writer.Allocating = .init(allocator);
    defer out.deinit();
    try out.writer.writeAll("{\"mapping\":");
    try canonical_json.writeCanonicalJson(allocator, &out.writer, mapping);
    try out.writer.writeAll(",\"nonce\":");
    try canonical_json.writeCanonicalString(&out.writer, nonce);
    try out.writer.writeAll(",\"schema\":\"hylo-arm-map/v1\",\"trial_id\":");
    try canonical_json.writeCanonicalString(&out.writer, trial_id);
    try out.writer.writeByte('}');
    return canonical_json.digestBytesAlloc(allocator, out.written());
}

fn treatmentOpeningForArmInOpening(
    opening: std.json.ObjectMap,
    arm_id: []const u8,
) !std.json.ObjectMap {
    var matched: ?std.json.ObjectMap = null;
    for ((try requiredArray(opening, "treatments")).items) |value| {
        const treatment = try object(value);
        if (!std.mem.eql(u8, try requiredString(treatment, "arm_id"), arm_id)) continue;
        if (matched != null) return error.CustodyTreatmentDuplicate;
        matched = treatment;
    }
    return matched orelse error.CustodyTreatmentMissing;
}

pub fn treatmentOpeningForArm(
    custody: std.json.ObjectMap,
    arm_id: []const u8,
) !std.json.ObjectMap {
    return treatmentOpeningForArmInOpening(try requiredObject(custody, "opening"), arm_id);
}

pub fn materializationForArm(
    custody: std.json.ObjectMap,
    arm_id: []const u8,
) !std.json.Value {
    var matched: ?std.json.Value = null;
    for ((try requiredArray(custody, "materializations")).items) |value| {
        const entry = try object(value);
        if (!std.mem.eql(u8, try requiredString(entry, "arm_id"), arm_id)) continue;
        if (matched != null) return error.CustodyMaterializationDuplicate;
        matched = try required(entry, "materialization");
    }
    return matched orelse error.CustodyMaterializationMissing;
}

pub fn semanticRoleForArm(custody: std.json.ObjectMap, arm_id: []const u8) ![]const u8 {
    return requiredString(try treatmentOpeningForArm(custody, arm_id), "semantic_role");
}

fn mappingFromOpeningAlloc(
    allocator: std.mem.Allocator,
    public_trial: std.json.ObjectMap,
    opening: std.json.ObjectMap,
) ![]u8 {
    const arms = try requiredArray(public_trial, "arms");
    if (arms.items.len != 2) return error.CustodyArmShapeInvalid;
    var out: std.Io.Writer.Allocating = .init(allocator);
    defer out.deinit();
    try out.writer.writeByte('{');
    for (arms.items, 0..) |arm_value, index| {
        if (index != 0) try out.writer.writeByte(',');
        const arm_id = try requiredString(try object(arm_value), "arm_id");
        try canonical_json.writeCanonicalString(&out.writer, arm_id);
        try out.writer.writeByte(':');
        const treatment = try treatmentOpeningForArmInOpening(opening, arm_id);
        try canonical_json.writeCanonicalString(
            &out.writer,
            try requiredString(treatment, "semantic_role"),
        );
    }
    try out.writer.writeByte('}');
    return out.toOwnedSlice();
}

pub fn mappingAlloc(
    allocator: std.mem.Allocator,
    public_trial: std.json.ObjectMap,
    custody: std.json.ObjectMap,
) ![]u8 {
    return mappingFromOpeningAlloc(allocator, public_trial, try requiredObject(custody, "opening"));
}

pub fn validateOpening(
    allocator: std.mem.Allocator,
    public_trial_value: std.json.Value,
    opening_value: std.json.Value,
) !void {
    const public_trial = try object(public_trial_value);
    const opening = try object(opening_value);
    const trial_id = try validateOpeningHeader(public_trial, opening);
    try validateTreatmentOpenings(allocator, public_trial, opening);
    try validateArmMapOpening(allocator, public_trial, opening, trial_id);
    try validateTargetEpochOpening(allocator, public_trial, opening);
    try validateWitnessOpening(allocator, public_trial, opening);
    try validateProjectionOpening(allocator, public_trial, opening);

    const custody_commitment = try digestValueAlloc(allocator, opening_value);
    defer allocator.free(custody_commitment);
    if (!std.mem.eql(
        u8,
        custody_commitment,
        try requiredString(public_trial, "custody_commitment"),
    )) {
        return error.CustodyCommitmentMismatch;
    }
}

fn validateOpeningHeader(
    public_trial: std.json.ObjectMap,
    opening: std.json.ObjectMap,
) ![]const u8 {
    if (!std.mem.eql(u8, try requiredString(public_trial, "schema"), PublicTrialSchema) or
        !std.mem.eql(u8, try requiredString(opening, "schema"), CustodyOpeningSchema))
    {
        return error.CustodyOpeningInvalid;
    }
    try requireExactKeys(opening, &.{
        "arm_map_nonce",
        "intervention_witness",
        "schema",
        "source_selection_commitment",
        "target_common_projection",
        "target_epoch",
        "treatments",
        "trial_id",
    });
    const trial_id = try requiredString(public_trial, "trial_id");
    if (!std.mem.eql(u8, try requiredString(opening, "trial_id"), trial_id)) {
        return error.CustodyTrialMismatch;
    }
    const source_selection_commitment = try requiredString(opening, "source_selection_commitment");
    try validateFingerprint(source_selection_commitment);
    if (!std.mem.eql(
        u8,
        source_selection_commitment,
        try requiredString(
            try requiredObject(public_trial, "sealing"),
            "source_selection_receipt_commitment",
        ),
    )) return error.CustodySourceSelectionCommitmentMismatch;
    return trial_id;
}

fn validateTreatmentOpenings(
    allocator: std.mem.Allocator,
    public_trial: std.json.ObjectMap,
    opening: std.json.ObjectMap,
) !void {
    const arms = try requiredArray(public_trial, "arms");
    const treatments = try requiredArray(opening, "treatments");
    if (arms.items.len != 2 or treatments.items.len != 2) {
        return error.CustodyArmShapeInvalid;
    }
    var baseline_count: usize = 0;
    var candidate_count: usize = 0;
    for (arms.items) |arm_value| {
        const arm = try object(arm_value);
        const arm_id = try requiredString(arm, "arm_id");
        const treatment = try treatmentOpeningForArmInOpening(opening, arm_id);
        try requireExactKeys(treatment, &.{
            "arm_id",
            "materialization_fingerprint",
            "materialization_ref",
            "nonce",
            "schema",
            "semantic_role",
            "value_fingerprint",
        });
        if (!std.mem.eql(u8, try requiredString(treatment, "schema"), TreatmentOpeningSchema)) {
            return error.CustodyTreatmentInvalid;
        }
        const role = try requiredString(treatment, "semantic_role");
        if (std.mem.eql(u8, role, "baseline")) {
            baseline_count += 1;
        } else if (std.mem.eql(u8, role, "candidate")) {
            candidate_count += 1;
        } else return error.CustodyTreatmentInvalid;
        try validateFingerprint(try requiredString(treatment, "value_fingerprint"));
        try validateFingerprint(try requiredString(treatment, "materialization_fingerprint"));
        _ = try requiredString(treatment, "materialization_ref");
        try validateNonce(try requiredString(treatment, "nonce"));
        const treatment_commitment = try treatmentCommitmentAlloc(allocator, treatment);
        defer allocator.free(treatment_commitment);
        if (!std.mem.eql(
            u8,
            treatment_commitment,
            try requiredString(arm, "treatment_commitment"),
        )) return error.CustodyTreatmentCommitmentMismatch;
    }
    if (baseline_count != 1 or candidate_count != 1) return error.CustodySemanticMapInvalid;
}

fn validateArmMapOpening(
    allocator: std.mem.Allocator,
    public_trial: std.json.ObjectMap,
    opening: std.json.ObjectMap,
    trial_id: []const u8,
) !void {
    const mapping_bytes = try mappingFromOpeningAlloc(allocator, public_trial, opening);
    defer allocator.free(mapping_bytes);
    var mapping = try std.json.parseFromSlice(std.json.Value, allocator, mapping_bytes, .{
        .allocate = .alloc_always,
        .duplicate_field_behavior = .@"error",
    });
    defer mapping.deinit();
    const arm_map_nonce = try requiredString(opening, "arm_map_nonce");
    try validateArmMapNonce(arm_map_nonce);
    const arm_map_commitment = try armMapCommitmentAlloc(
        allocator,
        trial_id,
        mapping.value,
        arm_map_nonce,
    );
    defer allocator.free(arm_map_commitment);
    if (!std.mem.eql(
        u8,
        arm_map_commitment,
        try requiredString(try requiredObject(public_trial, "arm_map_commitment"), "fingerprint"),
    )) return error.CustodyArmMapCommitmentMismatch;
}

fn validateTargetEpochOpening(
    allocator: std.mem.Allocator,
    public_trial: std.json.ObjectMap,
    opening: std.json.ObjectMap,
) !void {
    const target_epoch = try requiredObject(public_trial, "target_epoch");
    const target_opening = try requiredObject(opening, "target_epoch");
    try requireExactKeys(target_opening, &.{ "after", "before", "change" });
    const before = try requiredObject(target_opening, "before");
    const after = try requiredObject(target_opening, "after");
    const change = try requiredObject(target_opening, "change");
    try requireExactKeys(before, &.{ "nonce", "schema", "semantic_role", "target_fingerprint" });
    try requireExactKeys(after, &.{ "nonce", "schema", "semantic_role", "target_fingerprint" });
    try requireExactKeys(change, &.{ "change_id", "nonce", "schema" });
    if (!std.mem.eql(u8, try requiredString(before, "schema"), TargetOpeningSchema) or
        !std.mem.eql(u8, try requiredString(before, "semantic_role"), "baseline") or
        !std.mem.eql(u8, try requiredString(after, "schema"), TargetOpeningSchema) or
        !std.mem.eql(u8, try requiredString(after, "semantic_role"), "candidate") or
        !std.mem.eql(u8, try requiredString(change, "schema"), ChangeOpeningSchema))
    {
        return error.CustodyTargetOpeningInvalid;
    }
    for ([_]std.json.ObjectMap{ before, after, change }) |entry| {
        try validateNonce(try requiredString(entry, "nonce"));
    }
    try validateFingerprint(try requiredString(before, "target_fingerprint"));
    try validateFingerprint(try requiredString(after, "target_fingerprint"));
    const before_commitment = try digestValueAlloc(allocator, .{ .object = before });
    defer allocator.free(before_commitment);
    const after_commitment = try digestValueAlloc(allocator, .{ .object = after });
    defer allocator.free(after_commitment);
    const change_commitment = try digestValueAlloc(allocator, .{ .object = change });
    defer allocator.free(change_commitment);
    if (!std.mem.eql(
        u8,
        before_commitment,
        try requiredString(target_epoch, "before_target_commitment"),
    ) or !std.mem.eql(
        u8,
        after_commitment,
        try requiredString(target_epoch, "after_target_commitment"),
    ) or
        !std.mem.eql(u8, change_commitment, try requiredString(target_epoch, "change_commitment")))
    {
        return error.CustodyTargetCommitmentMismatch;
    }
    try validateTargetTreatmentBindings(opening, before, after);
}

fn validateTargetTreatmentBindings(
    opening: std.json.ObjectMap,
    before: std.json.ObjectMap,
    after: std.json.ObjectMap,
) !void {
    for ((try requiredArray(opening, "treatments")).items) |treatment_value| {
        const treatment = try object(treatment_value);
        const role = try requiredString(treatment, "semantic_role");
        const expected = if (std.mem.eql(u8, role, "baseline"))
            try requiredString(before, "target_fingerprint")
        else
            try requiredString(after, "target_fingerprint");
        if (!std.mem.eql(u8, expected, try requiredString(treatment, "value_fingerprint"))) {
            return error.CustodyTargetTreatmentMismatch;
        }
    }
}

fn validateWitnessOpening(
    allocator: std.mem.Allocator,
    public_trial: std.json.ObjectMap,
    opening: std.json.ObjectMap,
) !void {
    const witness_opening_value = try required(opening, "intervention_witness");
    const witness_opening = try object(witness_opening_value);
    try requireExactKeys(witness_opening, &.{ "nonce", "schema", "witness" });
    if (!std.mem.eql(u8, try requiredString(witness_opening, "schema"), WitnessOpeningSchema)) {
        return error.CustodyWitnessInvalid;
    }
    try validateNonce(try requiredString(witness_opening, "nonce"));
    _ = try requiredObject(witness_opening, "witness");
    const witness_commitment = try digestValueAlloc(allocator, witness_opening_value);
    defer allocator.free(witness_commitment);
    if (!std.mem.eql(
        u8,
        witness_commitment,
        try requiredString(
            try requiredObject(public_trial, "factor"),
            "intervention_witness_commitment",
        ),
    )) return error.CustodyWitnessCommitmentMismatch;
}

fn validateProjectionOpening(
    allocator: std.mem.Allocator,
    public_trial: std.json.ObjectMap,
    opening: std.json.ObjectMap,
) !void {
    const factor = try requiredObject(public_trial, "factor");
    const projection_opening_value = try required(opening, "target_common_projection");
    const projection_opening = try object(projection_opening_value);
    try requireExactKeys(projection_opening, &.{ "nonce", "projection", "schema" });
    if (!std.mem.eql(
        u8,
        try requiredString(projection_opening, "schema"),
        TargetCommonProjectionOpeningSchema,
    )) return error.CustodyTargetCommonProjectionInvalid;
    try validateNonce(try requiredString(projection_opening, "nonce"));
    const projection_value = try required(projection_opening, "projection");
    _ = try object(projection_value);
    const projection_fingerprint = try digestValueAlloc(allocator, projection_value);
    defer allocator.free(projection_fingerprint);
    if (!std.mem.eql(
        u8,
        projection_fingerprint,
        try requiredString(factor, "common_projection_fingerprint"),
    )) return error.CustodyTargetCommonProjectionMismatch;
    const projection_commitment = try digestValueAlloc(allocator, projection_opening_value);
    defer allocator.free(projection_commitment);
    if (!std.mem.eql(
        u8,
        projection_commitment,
        try requiredString(factor, "target_common_projection_commitment"),
    )) return error.CustodyTargetCommonProjectionCommitmentMismatch;
}

pub const RevealValidation = struct {
    baseline_arm_id: []const u8,
    candidate_arm_id: []const u8,
};

/// Borrowed semantic evidence that becomes public only through one validated
/// `hylo-trial-reveal/v2`. Callers must retain the parsed trial and reveal for
/// the lifetime of this view. This intentionally exposes no custody
/// materialization body or source-selection opening.
pub const RevealedEvidence = struct {
    baseline_arm_id: []const u8,
    candidate_arm_id: []const u8,
    baseline_treatment: std.json.ObjectMap,
    candidate_treatment: std.json.ObjectMap,
    before_target: std.json.ObjectMap,
    after_target: std.json.ObjectMap,
    change: std.json.ObjectMap,
    intervention_witness: std.json.Value,
    target_common_projection: std.json.Value,
};

fn trialHasLane(public_trial: std.json.ObjectMap, lane_id: []const u8) !bool {
    for ((try requiredArray(public_trial, "units")).items) |unit_value| {
        const unit = try object(unit_value);
        for ((try requiredArray(unit, "pairs")).items) |pair_value| {
            const lanes = try requiredObject(try object(pair_value), "lanes");
            var iterator = lanes.iterator();
            while (iterator.next()) |entry| {
                if (std.mem.eql(
                    u8,
                    try requiredString(try object(entry.value_ptr.*), "lane_id"),
                    lane_id,
                )) return true;
            }
        }
    }
    return false;
}

fn trialLaneCount(public_trial: std.json.ObjectMap) !usize {
    var count: usize = 0;
    for ((try requiredArray(public_trial, "units")).items) |unit_value| {
        const unit = try object(unit_value);
        for ((try requiredArray(unit, "pairs")).items) |pair_value| {
            count += (try requiredObject(try object(pair_value), "lanes")).count();
        }
    }
    return count;
}

fn stringArrayContains(items: std.json.Array, wanted: []const u8) !bool {
    for (items.items) |item| {
        if (std.mem.eql(u8, try string(item), wanted)) return true;
    }
    return false;
}

pub fn validateMaterializerEvidence(
    public_trial_value: std.json.Value,
    reveal_value: std.json.Value,
) !void {
    const public_trial = try object(public_trial_value);
    const reveal = try object(reveal_value);
    const trial_id = try requiredString(public_trial, "trial_id");
    const materialization_receipts = try requiredArray(reveal, "materialization_receipts");
    for (materialization_receipts.items, 0..) |receipt_value, index| {
        const receipt = try object(receipt_value);
        try validateMaterializationReceipt(public_trial, receipt, trial_id);
        const lane_id = try requiredString(receipt, "lane_id");
        for (materialization_receipts.items[0..index]) |previous_value| {
            if (std.mem.eql(
                u8,
                try requiredString(try object(previous_value), "lane_id"),
                lane_id,
            )) return error.RevealMaterializationReceiptDuplicate;
        }
    }
    const materializer_key_id = try requiredMaterializerKeyId(public_trial);
    const materializer_validations = try requiredArray(reveal, "materializer_validations");
    const lane_count = try trialLaneCount(public_trial);
    if (materializer_key_id != null) {
        if (materialization_receipts.items.len != lane_count or
            materializer_validations.items.len != lane_count)
        {
            return error.SealedMaterializationMissing;
        }
    } else if (materializer_validations.items.len != 0) {
        return error.RevealMaterializerValidationInvalid;
    }
    for (materializer_validations.items, 0..) |validation_value, index| {
        const validation = try object(validation_value);
        try validateMaterializerValidation(
            public_trial,
            validation,
            trial_id,
            materializer_key_id,
        );
        const lane_id = try requiredString(validation, "lane_id");
        for (materializer_validations.items[0..index]) |previous_value| {
            if (std.mem.eql(
                u8,
                try requiredString(try object(previous_value), "lane_id"),
                lane_id,
            )) return error.RevealMaterializerValidationDuplicate;
        }
    }
}

fn validateMaterializationReceipt(
    public_trial: std.json.ObjectMap,
    receipt: std.json.ObjectMap,
    trial_id: []const u8,
) !void {
    requireExactKeys(receipt, &.{
        "claim_fingerprint",
        "delivered_by_fd",
        "lane_id",
        "schema",
        "semantic_role_disclosed",
        "trial_id",
    }) catch return error.RevealMaterializationReceiptInvalid;
    if (!std.mem.eql(
        u8,
        try requiredString(receipt, "schema"),
        "hylo-lane-materialization-receipt/v2",
    ) or !std.mem.eql(u8, try requiredString(receipt, "trial_id"), trial_id) or
        !try boolean(try required(receipt, "delivered_by_fd")) or
        try boolean(try required(receipt, "semantic_role_disclosed")))
    {
        return error.RevealMaterializationReceiptInvalid;
    }
    try validateFingerprint(try requiredString(receipt, "claim_fingerprint"));
    if (!try trialHasLane(public_trial, try requiredString(receipt, "lane_id"))) {
        return error.RevealMaterializationReceiptInvalid;
    }
}

fn requiredMaterializerKeyId(public_trial: std.json.ObjectMap) !?[]const u8 {
    const assurance = try requiredObject(public_trial, "assurance");
    const assurance_level = try requiredString(assurance, "required_level");
    const is_required = std.mem.eql(u8, assurance_level, "sealed") or
        (std.mem.eql(u8, assurance_level, "role_separated") and
            try stringArrayContains(
                try requiredArray(assurance, "required_distinct_roles"),
                "materializer",
            ));
    if (!is_required) return null;
    return try requiredString(
        try requiredObject(
            try requiredObject(public_trial, "sealing"),
            "case_materializer_contract",
        ),
        "materializer_key_id",
    );
}

fn validateMaterializerValidation(
    public_trial: std.json.ObjectMap,
    validation: std.json.ObjectMap,
    trial_id: []const u8,
    materializer_key_id: ?[]const u8,
) !void {
    requireExactKeys(validation, &.{
        "lane_id",
        "materializer_key_id",
        "private_receipt_disclosed",
        "private_receipt_fingerprint",
        "schema",
        "semantic_evidence_returned",
        "semantic_material_persisted",
        "trial_id",
        "validated",
    }) catch return error.RevealMaterializerValidationInvalid;
    if (!std.mem.eql(
        u8,
        try requiredString(validation, "schema"),
        MaterializerValidationSchema,
    ) or !std.mem.eql(u8, try requiredString(validation, "trial_id"), trial_id) or
        materializer_key_id == null or
        !std.mem.eql(
            u8,
            try requiredString(validation, "materializer_key_id"),
            materializer_key_id.?,
        ) or !try boolean(try required(validation, "validated")) or
        try boolean(try required(validation, "private_receipt_disclosed")) or
        try boolean(try required(validation, "semantic_evidence_returned")) or
        try boolean(try required(validation, "semantic_material_persisted")))
    {
        return error.RevealMaterializerValidationInvalid;
    }
    try validateFingerprint(try requiredString(validation, "private_receipt_fingerprint"));
    if (!try trialHasLane(public_trial, try requiredString(validation, "lane_id"))) {
        return error.RevealMaterializerValidationInvalid;
    }
}

pub fn validateReveal(
    allocator: std.mem.Allocator,
    public_trial_value: std.json.Value,
    reveal_value: std.json.Value,
) !RevealValidation {
    const public_trial = try object(public_trial_value);
    const reveal = try object(reveal_value);
    if (!std.mem.eql(u8, try requiredString(public_trial, "schema"), PublicTrialSchema) or
        !std.mem.eql(u8, try requiredString(reveal, "schema"), RevealSchema))
    {
        return error.RevealInvalid;
    }
    requireExactKeys(reveal, &.{
        "arm_map_nonce",
        "custody_opening",
        "mapping",
        "materialization_receipts",
        "materializer_validations",
        "revealed_at_scope",
        "schema",
        "trial_id",
    }) catch return error.RevealInvalid;
    const trial_id = try requiredString(public_trial, "trial_id");
    if (!std.mem.eql(u8, try requiredString(reveal, "trial_id"), trial_id)) {
        return error.CustodyTrialMismatch;
    }
    const opening_value = try required(reveal, "custody_opening");
    const opening = try object(opening_value);
    try validateOpening(allocator, public_trial_value, opening_value);
    const nonce = try requiredString(reveal, "arm_map_nonce");
    if (!std.mem.eql(u8, nonce, try requiredString(opening, "arm_map_nonce"))) {
        return error.RevealCommitmentMismatch;
    }
    const result = try validateRevealMapping(allocator, public_trial, reveal, opening);
    try validateMaterializerEvidence(public_trial_value, reveal_value);
    try validateRevealScope(public_trial, reveal);
    return result;
}

fn validateRevealMapping(
    allocator: std.mem.Allocator,
    public_trial: std.json.ObjectMap,
    reveal: std.json.ObjectMap,
    opening: std.json.ObjectMap,
) !RevealValidation {
    const expected_mapping_bytes = try mappingFromOpeningAlloc(allocator, public_trial, opening);
    defer allocator.free(expected_mapping_bytes);
    var expected_mapping = try std.json.parseFromSlice(
        std.json.Value,
        allocator,
        expected_mapping_bytes,
        .{
            .allocate = .alloc_always,
            .duplicate_field_behavior = .@"error",
        },
    );
    defer expected_mapping.deinit();
    const expected_mapping_fingerprint = try digestValueAlloc(allocator, expected_mapping.value);
    defer allocator.free(expected_mapping_fingerprint);
    const actual_mapping = try required(reveal, "mapping");
    const actual_mapping_object = try object(actual_mapping);
    if (actual_mapping_object.count() != 2) return error.RevealCommitmentMismatch;
    const actual_mapping_fingerprint = try digestValueAlloc(allocator, actual_mapping);
    defer allocator.free(actual_mapping_fingerprint);
    if (!std.mem.eql(u8, expected_mapping_fingerprint, actual_mapping_fingerprint)) {
        return error.RevealCommitmentMismatch;
    }

    const mapping = try object(actual_mapping);
    const arms = try requiredArray(public_trial, "arms");
    const arm0_id = try requiredString(try object(arms.items[0]), "arm_id");
    const arm1_id = try requiredString(try object(arms.items[1]), "arm_id");
    const arm0_semantic = try requiredString(mapping, arm0_id);
    return .{
        .baseline_arm_id = if (std.mem.eql(u8, arm0_semantic, "baseline")) arm0_id else arm1_id,
        .candidate_arm_id = if (std.mem.eql(u8, arm0_semantic, "candidate")) arm0_id else arm1_id,
    };
}

fn validateRevealScope(
    public_trial: std.json.ObjectMap,
    reveal: std.json.ObjectMap,
) !void {
    const scope = try requiredString(reveal, "revealed_at_scope");
    if (!std.mem.eql(u8, scope, "trial") and !std.mem.eql(u8, scope, "campaign_holdout")) {
        return error.RevealScopeInvalid;
    }
    if (!std.mem.eql(
        u8,
        scope,
        try requiredString(try requiredObject(public_trial, "sealing"), "reveal_scope"),
    )) return error.RevealScopeInvalid;
}

pub fn revealedEvidence(
    allocator: std.mem.Allocator,
    public_trial_value: std.json.Value,
    reveal_value: std.json.Value,
) !RevealedEvidence {
    const validated = try validateReveal(allocator, public_trial_value, reveal_value);
    const reveal = try object(reveal_value);
    const opening = try requiredObject(reveal, "custody_opening");
    const target_epoch = try requiredObject(opening, "target_epoch");
    return .{
        .baseline_arm_id = validated.baseline_arm_id,
        .candidate_arm_id = validated.candidate_arm_id,
        .baseline_treatment = try treatmentOpeningForArmInOpening(
            opening,
            validated.baseline_arm_id,
        ),
        .candidate_treatment = try treatmentOpeningForArmInOpening(
            opening,
            validated.candidate_arm_id,
        ),
        .before_target = try requiredObject(target_epoch, "before"),
        .after_target = try requiredObject(target_epoch, "after"),
        .change = try requiredObject(target_epoch, "change"),
        .intervention_witness = try required(
            try requiredObject(opening, "intervention_witness"),
            "witness",
        ),
        .target_common_projection = try required(
            try requiredObject(opening, "target_common_projection"),
            "projection",
        ),
    };
}

pub fn validateCustody(
    allocator: std.mem.Allocator,
    public_trial_value: std.json.Value,
    custody_value: std.json.Value,
) !void {
    const public_trial = try object(public_trial_value);
    const custody = try object(custody_value);
    try validateCustodyHeader(allocator, public_trial_value, public_trial, custody);

    const opening_value = try required(custody, "opening");
    try validateOpening(allocator, public_trial_value, opening_value);
    const opening = try object(opening_value);
    try validateSourceSelectionCustody(allocator, public_trial, custody, opening);
    try validateCustodyMaterializations(allocator, public_trial, custody, opening);
}

fn validateCustodyHeader(
    allocator: std.mem.Allocator,
    public_trial_value: std.json.Value,
    public_trial: std.json.ObjectMap,
    custody: std.json.ObjectMap,
) !void {
    if (!std.mem.eql(u8, try requiredString(public_trial, "schema"), PublicTrialSchema) or
        !std.mem.eql(u8, try requiredString(custody, "schema"), CustodySchema))
    {
        return error.CustodySchemaInvalid;
    }
    try requireExactKeys(custody, &.{
        "materializations",
        "opening",
        "public_trial_fingerprint",
        "schema",
        "source_selection",
        "trial_id",
    });
    const trial_id = try requiredString(public_trial, "trial_id");
    if (!std.mem.eql(u8, try requiredString(custody, "trial_id"), trial_id)) {
        return error.CustodyTrialMismatch;
    }
    const public_fingerprint = try digestValueAlloc(allocator, public_trial_value);
    defer allocator.free(public_fingerprint);
    if (!std.mem.eql(
        u8,
        public_fingerprint,
        try requiredString(custody, "public_trial_fingerprint"),
    )) {
        return error.CustodyTrialMismatch;
    }
}

fn validateSourceSelectionCustody(
    allocator: std.mem.Allocator,
    public_trial: std.json.ObjectMap,
    custody: std.json.ObjectMap,
    opening: std.json.ObjectMap,
) !void {
    const source_selection_value = try required(custody, "source_selection");
    const source_selection = try object(source_selection_value);
    try requireExactKeys(source_selection, &.{ "nonce", "receipt", "schema" });
    if (!std.mem.eql(
        u8,
        try requiredString(source_selection, "schema"),
        SourceSelectionOpeningSchema,
    )) return error.CustodySourceSelectionInvalid;
    try validateNonce(try requiredString(source_selection, "nonce"));
    const source_receipt = try required(source_selection, "receipt");
    const source_receipt_object = try object(source_receipt);
    const source_selection_commitment = try digestValueAlloc(allocator, source_selection_value);
    defer allocator.free(source_selection_commitment);
    if (!std.mem.eql(
        u8,
        source_selection_commitment,
        try requiredString(opening, "source_selection_commitment"),
    )) return error.CustodySourceSelectionCommitmentMismatch;
    const source_receipt_fingerprint = try requiredString(
        source_receipt_object,
        "receipt_fingerprint",
    );
    try validateFingerprint(source_receipt_fingerprint);
    if (!std.mem.eql(
        u8,
        source_receipt_fingerprint,
        try requiredString(
            try requiredObject(public_trial, "sealing"),
            "source_selection_receipt_fingerprint",
        ),
    )) return error.CustodySourceSelectionReceiptMismatch;
}

fn validateCustodyMaterializations(
    allocator: std.mem.Allocator,
    public_trial: std.json.ObjectMap,
    custody: std.json.ObjectMap,
    opening: std.json.ObjectMap,
) !void {
    const arms = try requiredArray(public_trial, "arms");
    const materializations = try requiredArray(custody, "materializations");
    if (arms.items.len != 2 or materializations.items.len != 2) {
        return error.CustodyArmShapeInvalid;
    }
    for (arms.items) |arm_value| {
        const arm = try object(arm_value);
        const arm_id = try requiredString(arm, "arm_id");
        const treatment = try treatmentOpeningForArmInOpening(opening, arm_id);
        const entry = try materializationEntryForArm(materializations, arm_id);
        try validateMaterializationEntry(entry, treatment);
        const materialization = try materializationForArm(custody, arm_id);
        const materialization_fingerprint = try digestValueAlloc(allocator, materialization);
        defer allocator.free(materialization_fingerprint);
        if (!std.mem.eql(
            u8,
            materialization_fingerprint,
            try requiredString(treatment, "materialization_fingerprint"),
        )) return error.CustodyMaterializationFingerprintMismatch;
    }
}

fn materializationEntryForArm(
    materializations: std.json.Array,
    arm_id: []const u8,
) !std.json.ObjectMap {
    var matched: ?std.json.ObjectMap = null;
    for (materializations.items) |value| {
        const entry = try object(value);
        if (!std.mem.eql(u8, try requiredString(entry, "arm_id"), arm_id)) continue;
        if (matched != null) return error.CustodyMaterializationDuplicate;
        matched = entry;
    }
    return matched orelse error.CustodyMaterializationMissing;
}

fn validateMaterializationEntry(
    entry: std.json.ObjectMap,
    treatment: std.json.ObjectMap,
) !void {
    try requireExactKeys(entry, &.{
        "arm_id",
        "materialization",
        "materialization_fingerprint",
        "materialization_ref",
        "schema",
        "value_fingerprint",
    });
    if (!std.mem.eql(
        u8,
        try requiredString(entry, "schema"),
        "hylo-arm-materialization/v1",
    ) or !std.mem.eql(
        u8,
        try requiredString(entry, "value_fingerprint"),
        try requiredString(treatment, "value_fingerprint"),
    ) or !std.mem.eql(
        u8,
        try requiredString(entry, "materialization_fingerprint"),
        try requiredString(treatment, "materialization_fingerprint"),
    ) or !std.mem.eql(
        u8,
        try requiredString(entry, "materialization_ref"),
        try requiredString(treatment, "materialization_ref"),
    )) return error.CustodyMaterializationInvalid;
}

test "v2 custody nonce grammar accepts only the compiler's bare lowercase hex forms" {
    const arm_map_nonce = "00112233445566778899aabbccddeeff";
    const custody_nonce =
        "00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff";

    try validateArmMapNonce(arm_map_nonce);
    try validateNonce(custody_nonce);

    try std.testing.expectError(
        error.CustodyNonceInvalid,
        validateArmMapNonce("arm-map:00112233445566778899aabbccddeeff"),
    );
    try std.testing.expectError(
        error.CustodyNonceInvalid,
        validateNonce(
            "custody:00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff",
        ),
    );
    try std.testing.expectError(
        error.CustodyNonceInvalid,
        validateArmMapNonce("00112233445566778899AABBCCDDEEFF"),
    );
    try std.testing.expectError(
        error.CustodyNonceInvalid,
        validateNonce(
            "00112233445566778899aabbccddeeff00112233445566778899aabbccddeezz",
        ),
    );
}

const role_separated_public_trial_json =
    "{\"trial_id\":\"trial-private\",\"assurance\":{" ++
    "\"required_level\":\"role_separated\"," ++
    "\"required_distinct_roles\":[\"runner\",\"materializer\"]}," ++
    "\"sealing\":{\"case_materializer_contract\":{" ++
    "\"materializer_key_id\":\"materializer-key\"}}," ++
    "\"units\":[{\"pairs\":[{\"lanes\":{" ++
    "\"arm-a\":{\"lane_id\":\"lane-a\"}," ++
    "\"arm-b\":{\"lane_id\":\"lane-b\"}}}]}]}";

const receipt_hash_a =
    "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
const receipt_hash_b =
    "sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb";
const receipt_hash_c =
    "sha256:cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc";
const receipt_hash_d =
    "sha256:dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd";

const lane_a_receipt_json =
    "{\"claim_fingerprint\":\"" ++ receipt_hash_a ++ "\"," ++
    "\"delivered_by_fd\":true,\"lane_id\":\"lane-a\"," ++
    "\"schema\":\"hylo-lane-materialization-receipt/v2\"," ++
    "\"semantic_role_disclosed\":false,\"trial_id\":\"trial-private\"}";
const lane_b_receipt_json =
    "{\"claim_fingerprint\":\"" ++ receipt_hash_b ++ "\"," ++
    "\"delivered_by_fd\":true,\"lane_id\":\"lane-b\"," ++
    "\"schema\":\"hylo-lane-materialization-receipt/v2\"," ++
    "\"semantic_role_disclosed\":false,\"trial_id\":\"trial-private\"}";

const lane_a_validation_json =
    "{\"lane_id\":\"lane-a\",\"materializer_key_id\":\"materializer-key\"," ++
    "\"private_receipt_disclosed\":false,\"private_receipt_fingerprint\":\"" ++
    receipt_hash_c ++ "\",\"schema\":\"hylo-materializer-validation/v1\"," ++
    "\"semantic_evidence_returned\":false,\"semantic_material_persisted\":false," ++
    "\"trial_id\":\"trial-private\",\"validated\":true}";
const lane_b_validation_json =
    "{\"lane_id\":\"lane-b\",\"materializer_key_id\":\"materializer-key\"," ++
    "\"private_receipt_disclosed\":false,\"private_receipt_fingerprint\":\"" ++
    receipt_hash_d ++ "\",\"schema\":\"hylo-materializer-validation/v1\"," ++
    "\"semantic_evidence_returned\":false,\"semantic_material_persisted\":false," ++
    "\"trial_id\":\"trial-private\",\"validated\":true}";

const role_separated_reveal_json =
    "{\"materialization_receipts\":[" ++ lane_a_receipt_json ++ "," ++
    lane_b_receipt_json ++ "],\"materializer_validations\":[" ++
    lane_a_validation_json ++ "," ++ lane_b_validation_json ++ "]}";

test "role-separated v2 reveal publishes only validated materializer commitments" {
    var public_trial = try std.json.parseFromSlice(
        std.json.Value,
        std.testing.allocator,
        role_separated_public_trial_json,
        .{},
    );
    defer public_trial.deinit();
    var reveal = try std.json.parseFromSlice(
        std.json.Value,
        std.testing.allocator,
        role_separated_reveal_json,
        .{},
    );
    defer reveal.deinit();
    try validateMaterializerEvidence(public_trial.value, reveal.value);
    try expectMissingMaterializationRejected(public_trial.value);
    try expectDisclosedMaterializationRejected(public_trial.value);
    try expectMaterializationSmugglingRejected(public_trial.value);
}

fn expectMissingMaterializationRejected(public_trial: std.json.Value) !void {
    const missing = try std.mem.replaceOwned(
        u8,
        std.testing.allocator,
        role_separated_reveal_json,
        "," ++ lane_b_validation_json,
        "",
    );
    defer std.testing.allocator.free(missing);
    var missing_value = try std.json.parseFromSlice(
        std.json.Value,
        std.testing.allocator,
        missing,
        .{},
    );
    defer missing_value.deinit();
    try std.testing.expectError(
        error.SealedMaterializationMissing,
        validateMaterializerEvidence(public_trial, missing_value.value),
    );
}

fn expectDisclosedMaterializationRejected(public_trial: std.json.Value) !void {
    const disclosed = try std.mem.replaceOwned(
        u8,
        std.testing.allocator,
        role_separated_reveal_json,
        "\"private_receipt_disclosed\":false",
        "\"private_receipt_disclosed\":true",
    );
    defer std.testing.allocator.free(disclosed);
    var disclosed_value = try std.json.parseFromSlice(
        std.json.Value,
        std.testing.allocator,
        disclosed,
        .{},
    );
    defer disclosed_value.deinit();
    try std.testing.expectError(
        error.RevealMaterializerValidationInvalid,
        validateMaterializerEvidence(public_trial, disclosed_value.value),
    );
}

fn expectMaterializationSmugglingRejected(public_trial: std.json.Value) !void {
    const smuggled = try std.mem.replaceOwned(
        u8,
        std.testing.allocator,
        role_separated_reveal_json,
        "\"validated\":true}",
        "\"validated\":true,\"source_profile\":{}}",
    );
    defer std.testing.allocator.free(smuggled);
    var smuggled_value = try std.json.parseFromSlice(
        std.json.Value,
        std.testing.allocator,
        smuggled,
        .{},
    );
    defer smuggled_value.deinit();
    try std.testing.expectError(
        error.RevealMaterializerValidationInvalid,
        validateMaterializerEvidence(public_trial, smuggled_value.value),
    );
}
