const retrace_core = @import("retrace_core");

comptime {
    _ = @import("lib.zig");
    _ = @import("tests/correctness_golden.zig");
    _ = @import("tests/fuzz_regression.zig");
    _ = @import("tests/allocation_failure.zig");
    _ = @import("types/spec.zig");
    _ = @import("query/mod.zig");
    _ = @import("query/engine.zig");
    _ = @import("output/mod.zig");
    _ = @import("commands/mod.zig");
    _ = @import("cli/registry.zig");
    _ = @import("cli/options.zig");
    _ = @import("cli/help.zig");
    _ = @import("cli/validate.zig");
    _ = retrace_core.canonical_trace;
    _ = @import("scan_plan.zig");
    _ = @import("session_scan.zig");
    _ = @import("datasets/mod.zig");
    _ = @import("plan_blocks.zig");
    _ = @import("datasets/messages.zig");
    _ = @import("datasets/skill_mentions.zig");
    _ = @import("datasets/skill_blocks.zig");
    _ = @import("datasets/token_events.zig");
    _ = @import("datasets/token_deltas.zig");
    _ = @import("datasets/token_sessions.zig");
    _ = @import("token_cost.zig");
    _ = @import("skill_contract.zig");
    _ = @import("skill_decision_receipt.zig");
    _ = @import("skill_decision_signals.zig");
    _ = retrace_core.dcp_schema;
    _ = retrace_core.decision_anchor;
    _ = @import("historical_decisions.zig");
    _ = @import("decision_capsule.zig");
    _ = @import("datasets/tool_calls.zig");
    _ = @import("datasets/memory_files.zig");
    _ = @import("datasets/memory_blocks.zig");
    _ = @import("datasets/codex_state_sqlite.zig");
    _ = @import("datasets/memory_stage1_outputs.zig");
    _ = @import("datasets/memory_extensions.zig");
    _ = @import("datasets/opencode_prompts.zig");
    _ = @import("datasets/opencode_events.zig");
    _ = @import("datasets/opencode_sqlite.zig");
    _ = @import("perf_cli.zig");
    _ = @import("perf_parser.zig");
    _ = @import("main.zig");
}

const std = @import("std");
const lib = @import("lib.zig");

test "bootstrap parse coverage" {
    try std.testing.expectEqual(lib.Command.skills_rank, lib.parseCommand("skills-rank"));
    try std.testing.expectEqual(lib.Command.skill_success_rank, lib.parseCommand("skill-success-rank"));
    try std.testing.expectEqual(lib.Command.skill_trend, lib.parseCommand("skill-trend"));
    try std.testing.expectEqual(lib.Command.skill_report, lib.parseCommand("skill-report"));
    try std.testing.expectEqual(lib.Command.skill_audit, lib.parseCommand("skill-audit"));
    try std.testing.expectEqual(lib.Command.skill_decision_audit, lib.parseCommand("skill-decision-audit"));
    try std.testing.expectEqual(lib.Command.skill_contract, lib.parseCommand("skill-contract"));
    try std.testing.expectEqual(lib.Command.skill_decision_receipt, lib.parseCommand("skill-decision-receipt"));
    try std.testing.expectEqual(lib.Command.decision_capsule, lib.parseCommand("decision-capsule"));
    try std.testing.expectEqual(lib.Command.skill_blocks, lib.parseCommand("skill-blocks"));
    try std.testing.expectEqual(lib.Command.artifact_search, lib.parseCommand("artifact-search"));
    try std.testing.expectEqual(lib.Command.tool_audit, lib.parseCommand("tool-audit"));
    try std.testing.expectEqual(lib.Command.memory_inventory, lib.parseCommand("memory-inventory"));
    try std.testing.expectEqual(lib.Command.message_search, lib.parseCommand("message-search"));
    try std.testing.expectEqual(lib.Command.message_audit, lib.parseCommand("message-audit"));
    try std.testing.expectEqual(lib.Command.skill_cohort, lib.parseCommand("skill-cohort"));
    try std.testing.expectEqual(lib.Command.tool_search, lib.parseCommand("tool-search"));
    try std.testing.expectEqual(lib.Command.memory_extension_audit, lib.parseCommand("memory-extension-audit"));
    try std.testing.expectEqual(lib.Command.token_window, lib.parseCommand("token-window"));
    try std.testing.expectEqual(lib.Command.workdir_report, lib.parseCommand("workdir-report"));
    try std.testing.expectEqual(lib.Command.role_breakdown, lib.parseCommand("role-breakdown"));
    try std.testing.expectEqual(lib.Command.occurrence_export, lib.parseCommand("occurrence-export"));
    try std.testing.expectEqual(lib.Command.orchestration_concurrency, lib.parseCommand("orchestration-concurrency"));
    try std.testing.expectEqual(lib.Command.find_session, lib.parseCommand("find-session"));
    try std.testing.expectEqual(lib.Command.plan_search, lib.parseCommand("plan-search"));
    try std.testing.expectEqual(lib.Command.reply_latency, lib.parseCommand("reply-latency"));
    try std.testing.expectEqual(lib.Command.session_prompts, lib.parseCommand("session-prompts"));
    try std.testing.expectEqual(lib.Command.report_bundle, lib.parseCommand("report-bundle"));
    try std.testing.expectEqual(lib.Command.section_audit, lib.parseCommand("section-audit"));
    try std.testing.expectEqual(lib.Command.token_usage, lib.parseCommand("token-usage"));
    try std.testing.expectEqual(lib.Command.token_cost, lib.parseCommand("token-cost"));
    try std.testing.expectEqual(lib.Command.routing_gap, lib.parseCommand("routing-gap"));
    try std.testing.expectEqual(lib.Command.datasets, lib.parseCommand("datasets"));
    try std.testing.expectEqual(lib.Command.dataset_schema, lib.parseCommand("dataset-schema"));
    try std.testing.expectEqual(lib.Command.query, lib.parseCommand("query"));
    try std.testing.expectEqual(lib.Command.goal_audit, lib.parseCommand("goal-audit"));
    try std.testing.expectEqual(lib.Command.resolve_churn_audit, lib.parseCommand("resolve-churn-audit"));
    try std.testing.expectEqual(lib.Command.review_compiler_audit, lib.parseCommand("review-compiler-audit"));
    try std.testing.expectEqual(lib.Command.workflow_audit, lib.parseCommand("workflow-audit"));
    try std.testing.expectEqual(lib.Command.workflow_overlap, lib.parseCommand("workflow-overlap"));
    try std.testing.expectEqual(lib.Command.session_tooling, lib.parseCommand("session-tooling"));
    try std.testing.expectEqual(lib.Command.query_diagnose, lib.parseCommand("query-diagnose"));
    try std.testing.expectEqual(lib.Command.capabilities, lib.parseCommand("capabilities"));
    try std.testing.expectEqual(lib.Command.memory_provenance, lib.parseCommand("memory-provenance"));
    try std.testing.expectEqual(lib.Command.memory_map, lib.parseCommand("memory-map"));
    try std.testing.expectEqual(lib.Command.memory_history, lib.parseCommand("memory-history"));
    try std.testing.expectEqual(lib.Command.opencode_prompts, lib.parseCommand("opencode-prompts"));
    try std.testing.expectEqual(lib.Command.opencode_events, lib.parseCommand("opencode-events"));
    try std.testing.expectEqual(lib.Command.index, lib.parseCommand("index"));
    try std.testing.expectEqual(lib.Command.unknown, lib.parseCommand("invalid"));
}

test "retrace core exposes DCP capsule primitives" {
    try std.testing.expectEqualStrings("DCP-v2", retrace_core.dcp_schema.version);
    _ = retrace_core.canonical_trace.CanonicalSessionTrace;
    _ = retrace_core.decision_anchor.Anchors;
}
